
'use strict';

const { SerialPort } = require('serialport');

const BAUD_RATE = 115200;
const COMMAND_TIMEOUT_MS = 5000;
const START_PAGE = 4;
const NDEF_OVERHEAD = 6;
const RETRY_DELAY_MS = 50;
const PAGE_RETRY = 5;

const PN532 = {
  INIT_COMMAND: Buffer.from([0x55,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0x03,0xfd,0xd4,0x14,0x01,0x17,0x00]),
  IN_RELEASE: Buffer.from([0x00,0x00,0xff,0x03,0xfd,0xd4,0x52,0x00,0xda,0x00]),
  QUERY: Buffer.from([0x00,0x00,0xff,0x04,0xfc,0xd4,0x4a,0x02,0x00,0xe0,0x00]),
  ACK: Buffer.from([0x00,0x00,0xff,0x00,0xff,0x00]),
  FRAME_START: Buffer.from([0x00,0x00,0xff]),
  TFI: 0xd5,
  RESP: { INIT:0x15, RELEASE:0x53, QUERY:0x4b, DATA:0x41 }
};

function sleep(ms){return new Promise(r=>setTimeout(r,ms));}
function buildFrame(payload){const len=payload.length;const lcs=(0x100-len)&0xff;const dcs=(0x100-payload.reduce((s,b)=>s+b,0))&0xff;return Buffer.concat([Buffer.from([0x00,0x00,0xff,len,lcs]),payload,Buffer.from([dcs,0x00])]);}
function parseResponse(buffer,startOffset=0){let pos=startOffset;while(pos<buffer.length){pos=buffer.indexOf(PN532.FRAME_START,pos);if(pos<0)return null;const avail=buffer.length-pos;if(avail<6)return null;if(buffer.subarray(pos,pos+6).equals(PN532.ACK)){pos+=6;continue;}if(avail<7)return null;const len=buffer[pos+3];const total=7+len;if(avail<total)return null;return {frame:buffer.subarray(pos,pos+total),endOffset:pos+total};}return null;}
function sendCommand(conn,command,expectedCode,timeout=COMMAND_TIMEOUT_MS){return new Promise(resolve=>{if(!conn?.isOpen)return resolve(null);let settled=false,buf=Buffer.alloc(0);const finish=r=>{if(settled)return;settled=true;clearTimeout(tid);conn.removeListener('data',onData);resolve(r);};const tryResolve=()=>{let off=0;while(true){const r=parseResponse(buf,off);if(!r)return false;if(r.frame.length>6&&r.frame[5]===PN532.TFI&&r.frame[6]===expectedCode){finish(r.frame);return true;}off=r.endOffset;}};const onData=d=>{buf=Buffer.concat([buf,d]);tryResolve();};const tid=setTimeout(()=>{if(!tryResolve())finish(null);},timeout);conn.on('data',onData);conn.write(command,err=>{if(err)finish(null);});});}
function openPort(portPath){return new Promise((resolve,reject)=>{const port=new SerialPort({path:portPath,baudRate:BAUD_RATE,autoOpen:false});port.open(err=>err?reject(err):resolve(port));});}
function closePort(connection){return new Promise(resolve=>{if(!connection||!connection.isOpen)return resolve();connection.close(()=>resolve());});}
async function initReader(conn){return Boolean(await sendCommand(conn,PN532.INIT_COMMAND,PN532.RESP.INIT));}
async function readPage(conn,page){for(let attempt=0;attempt<PAGE_RETRY;attempt++){const r=await sendCommand(conn,buildFrame(Buffer.from([0xd4,0x40,0x01,0x30,page])),PN532.RESP.DATA);if(r&&r[7]===0x00)return r.subarray(8,24);await sleep(RETRY_DELAY_MS);}return null;}
async function writePage(conn,page,data){for(let attempt=0;attempt<PAGE_RETRY;attempt++){const r=await sendCommand(conn,buildFrame(Buffer.from([0xd4,0x40,0x01,0xa2,page,...data])),PN532.RESP.DATA);if(r&&r[7]===0x00)return true;await sleep(RETRY_DELAY_MS);}return false;}
async function detectTag(conn){await sendCommand(conn,PN532.IN_RELEASE,PN532.RESP.RELEASE);const r=await sendCommand(conn,PN532.QUERY,PN532.RESP.QUERY);if(!r||r.length<=7||r[7]===0)return null;const idLen=r[12];const uid=r.subarray(13,13+idLen).toString('hex');await sleep(10);const header=await readPage(conn,0);if(!header)return null;const ccMagic=header[12];const cc2=header[14];if(ccMagic!==0xe1||cc2===0)return null;const userBytes=cc2*8;const endPage=START_PAGE+(userBytes/4)-1;const maxJsonBytes=userBytes-NDEF_OVERHEAD;return {uid,endPage,userBytes,maxJsonBytes};}
async function waitForTag(conn,timeoutMs=COMMAND_TIMEOUT_MS){const start=Date.now();do{const tag=await detectTag(conn);if(tag)return tag;await sleep(250);}while(Date.now()-start<timeoutMs);return null;}
function pageLabel(page){if(page<=1)return 'UID/SN';if(page===2)return 'UID/LOCK0';if(page===3)return 'CC';return 'USER';}
function pageObject(page,data,endPage){return {page,hex:[...data].map(b=>b.toString(16).padStart(2,'0')).join(' '),ascii:[...data].map(b=>(b>=0x20&&b<0x7f?String.fromCharCode(b):'.')).join(''),label:pageLabel(page),writable:page>=START_PAGE&&page<=endPage};}
function buildNdefMessage(jsonStr,maxBytes){const payload=Buffer.from(jsonStr,'utf8');if(payload.length>maxBytes)return null;const record=Buffer.concat([Buffer.from([0xd5,0x00,payload.length]),payload]);return Buffer.concat([Buffer.from([0x03,record.length]),record,Buffer.from([0xfe])]);}
function parseNdefJson(buffer){let i=0;while(i<buffer.length){const type=buffer[i];if(type===0x00){i++;continue;}if(type===0xfe)break;if(i+1>=buffer.length)return null;const len=buffer[i+1];if(type===0x03){const msg=buffer.subarray(i+2,i+2+len);if(msg.length<3)return null;const sr=(msg[0]>>4)&1;const typeLen=msg[1];const payloadLen=sr?msg[2]:msg.readUInt32BE(2);const hdr=sr?3:6;const payload=msg.subarray(hdr+typeLen,hdr+typeLen+payloadLen);try{return JSON.parse(payload.toString('utf8'));}catch{return null;}}i+=2+len;}return null;}
async function readAllPages(conn,tag){const pages=[];for(let p=0;p<=tag.endPage;p+=4){const data=await readPage(conn,p);if(!data)throw new Error(`NFC read failed at page ${p}`);const count=Math.min(4,tag.endPage-p+1);for(let i=0;i<count;i++)pages.push(pageObject(p+i,data.subarray(i*4,(i+1)*4),tag.endPage));}return pages;}
function getUserJson(pages){const userPages=pages.filter(p=>p.page>=START_PAGE);if(userPages.length===0)return null;const combined=Buffer.concat(userPages.map(p=>Buffer.from(p.hex.split(' ').map(x=>parseInt(x,16)))));return parseNdefJson(combined);}
function extractUserTextOrJson(json){if(json===null||json===undefined)return '';if(typeof json==='string')return json;if(typeof json==='object'){if(typeof json.value==='string')return json.value;if(typeof json.serial==='string')return json.serial;if(typeof json.nfcCode==='string')return json.nfcCode;if(typeof json.NFCCode==='string')return json.NFCCode;}return JSON.stringify(json);}
async function listSerialPorts(){const ports=await SerialPort.list();return ports.map(p=>({path:p.path,manufacturer:p.manufacturer||'',serialNumber:p.serialNumber||'',pnpId:p.pnpId||'',vendorId:p.vendorId||'',productId:p.productId||'',label:[p.path,p.manufacturer,p.pnpId].filter(Boolean).join(' | ')}));}
function scorePort(port){const text=`${port.path||''} ${port.manufacturer||''} ${port.pnpId||''}`.toLowerCase();let score=0;if(text.includes('pn532'))score+=100;if(text.includes('usb'))score+=40;if(text.includes('ch340')||text.includes('wch'))score+=30;if(text.includes('silicon labs')||text.includes('cp210'))score+=30;if(text.includes('ftdi'))score+=25;if(text.includes('acpi'))score-=30;if(text.includes('standard port types'))score-=20;return score;}
async function testConnection(portPath){let connection;try{connection=await openPort(portPath);const initialized=await initReader(connection);return {connected:Boolean(initialized),portPath,message:initialized?'PN532 connected':'PN532 did not respond'};}catch(err){return {connected:false,portPath,message:err?.message||String(err)};}finally{await closePort(connection);}}
async function autoDetectPort(){const ports=await listSerialPorts();const ordered=[...ports].sort((a,b)=>scorePort(b)-scorePort(a));for(const port of ordered){const result=await testConnection(port.path);if(result.connected)return {portPath:port.path,port,...result};}return null;}
async function readNfcTag(portPath,options={}){let connection;try{connection=await openPort(portPath);const initialized=await initReader(connection);if(!initialized)throw new Error('PN532 did not respond. Check port, reader, and wiring.');const tag=await waitForTag(connection,Number(options.timeoutMs||COMMAND_TIMEOUT_MS));if(!tag)throw new Error('No NFC tag found');const pages=await readAllPages(connection,tag);const json=getUserJson(pages);return {uid:tag.uid,userText:extractUserTextOrJson(json),json,pages,tagInfo:tag};}finally{await closePort(connection);}}
async function writeNfcTag(portPath,value,options={}){let connection;try{connection=await openPort(portPath);const initialized=await initReader(connection);if(!initialized)throw new Error('PN532 did not respond. Check port, reader, and wiring.');const tag=await waitForTag(connection,Number(options.timeoutMs||COMMAND_TIMEOUT_MS));if(!tag)throw new Error('No NFC tag found');let jsonStr=value;try{JSON.parse(value);}catch{jsonStr=JSON.stringify({value});}const data=buildNdefMessage(jsonStr,tag.maxJsonBytes);if(!data)throw new Error(`JSON too long. Max ${tag.maxJsonBytes} bytes`);const totalPages=Math.ceil(data.length/4);for(let i=0;i<totalPages;i++){const page=START_PAGE+i;const chunk=Buffer.alloc(4,0x00);data.copy(chunk,0,i*4,Math.min((i+1)*4,data.length));if(!(await writePage(connection,page,chunk)))throw new Error(`NFC write failed at page ${page}`);}const blank=Buffer.alloc(4,0x00);for(let p=START_PAGE+totalPages;p<=tag.endPage;p++){if(!(await writePage(connection,p,blank)))throw new Error(`NFC erase failed at page ${p}`);}return {uid:tag.uid,bytesWritten:data.length,pagesWritten:totalPages,maxJsonBytes:tag.maxJsonBytes};}finally{await closePort(connection);}}
async function eraseTag(portPath,options={}){let connection;try{connection=await openPort(portPath);const initialized=await initReader(connection);if(!initialized)throw new Error('PN532 did not respond. Check port, reader, and wiring.');const tag=await waitForTag(connection,Number(options.timeoutMs||COMMAND_TIMEOUT_MS));if(!tag)throw new Error('No NFC tag found');const blank=Buffer.alloc(4,0x00);for(let p=START_PAGE;p<=tag.endPage;p++){if(!(await writePage(connection,p,blank)))throw new Error(`NFC erase failed at page ${p}`);}return {uid:tag.uid,erasedPages:tag.endPage-START_PAGE+1};}finally{await closePort(connection);}}
module.exports={listSerialPorts,autoDetectPort,testConnection,readNfcTag,writeNfcTag,eraseTag,constants:{BAUD_RATE,START_PAGE,COMMAND_TIMEOUT_MS}};
